# YAML Alias and Anchor
static_layers_defaults: &static_layers_defaults
    type: "GeoJsonLayer"
    get_fill_color: [0, 0, 0, 0]
    get_line_color: [255, 0, 0, 255]
    line_width_min_pixels: 2
    pickable: "False"


static_layers:
    
    - <<: *static_layers_defaults
      name: "Postcodes"
      data: "data/geojson/ptv/boundaries/selected_postcodes_with_trams_trains.parquet"

    - <<: *static_layers_defaults
      name: "Commuting Hull Tiers Metro Tram"
      data: "data/geojson/ptv/ptv_commute_tier_hulls_metro_tram.parquet"
    
    - <<: *static_layers_defaults
      name: "Commuting Hull Tiers Metro Rail"
      data: "data/geojson/ptv/ptv_commute_tier_hulls_metro_rail.parquet"

    - <<: *static_layers_defaults
      name: "Isochrones Foot 5min"
      data: "data/isochrones_concatenated/foot/5.parquet"
      get_fill_color: [0, 0, 255, 50]

    - <<: *static_layers_defaults
      name: "Isochrones Foot 15min"
      data: "data/isochrones_concatenated/foot/15.parquet"
      get_fill_color: [0, 0, 255, 50]
      get_line_color: [0, 0, 255, 255]
    

    - <<: *static_layers_defaults
      name: "PTV Lines"
      data: "data/public_transport_lines.parquet"
      get_fill_color: [0, 0, 0, 0]
      get_line_color: [0, 255, 0, 255]

    - <<: *static_layers_defaults
      name: "PTV Stops"
      data: "data/geojson/ptv/stops_within_union.parquet"
      get_fill_color: [0, 0, 0, 0]
      get_line_color: [0, 255, 0, 255]

      
